name: integrations-tests

on:
  workflow_dispatch:
    inputs:
      dotnetTestVerbosity:
        description: 'dotnet test verbosity'     
        required: true
        default: 'normal'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup RabbitMQ
      uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3-management-alpine'
        host port: 5672
        rabbitmq user: 'guest'
        rabbitmq password: 'guest'
        rabbitmq vhost: '/'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Build
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
      run: |
        dotnet build --no-restore
    - name: Test
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
      run: |
        dotnet test --no-build --verbosity ${{ github.event.inputs.dotnetTestVerbosity }} ./tst/MCB.Core.Infra.CrossCutting.RabbitMq.IntegrationTests/MCB.Core.Infra.CrossCutting.RabbitMq.IntegrationTests.csproj
